/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.softauto.serializer.service;

import org.apache.avro.Protocol;
import org.softauto.serializer.CallFuture;

@org.apache.avro.specific.AvroGenerated
public interface SerializerService {
  public static final Protocol PROTOCOL = Protocol.parse("{\"protocol\":\"SerializerService\",\"namespace\":\"tests.infrastructure\",\"version\":\"1.0.0\",\"types\":[{\"name\" : \"org.softauto.serializer.service.Message\",\"type\" : \"external\"},{\"name\" : \"java.lang.Object\",\"type\" : \"external\"}],\"messages\":{\"execute\":{\"request\":[{\"name\":\"message\",\"type\":\"org.softauto.serializer.service.Message\"}],\"response\":{\"type\":\"java.lang.Object\"}}}}");


  /**
   */

  Object execute(Message message) throws Exception;

  @SuppressWarnings("all")
  public interface Callback extends SerializerService {
    public static final Protocol PROTOCOL = SerializerService.PROTOCOL;
    /**
     * @throws java.io.IOException The async call could not be completed.
     */

    void execute(Message message, CallFuture<Object> callback) throws Exception;
  }
}